### ISSUE TITLE
cylc review: issues inherited from rose bush origin

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc#2833]
**All GitHub issues concerning Rose Bush (to be closed in parallel under ``metomi/rose``) plus those informally registered in the migration PR #2614, collated here to aid systemisation & discussion post-migration to Cylc as Cylc Review.**

N.B. there is a new GitHub beta feature to transfer issues across repositories, but better to compile than transfer en-masse.

Can we agree on a (rough) prioritisation order, for anyone who has time to tackle any? We should also decide which 'feature request' issues should await the (later) development stages of a reformed Cylc Review as a component of the new Cylc GUI (#1873).

[Descriptions paraphrased given the overall, up-to-date context.]

#### Flaws or bugs:
- [ ] **https://github.com/cylc/cylc/pull/2614#discussion_r228457075 suite view broadcasts (states & events)**:
  - [ ] show empty tables not just blank pages (for feedback) for suites with no broadcasts;
  - [ ] raise appropriate HTTP status codes for non-existent relevant file/table & for lack of view permission.
- [ ] **suite metadata (see also https://github.com/cylc/cylc/pull/2614#issuecomment-430315439)** NB not marking these as duplicates as each concerns a separate aspect, as italicised:
  - [ ] metomi/rose#2147: *dynamic* metadata display (esp. for ``rosie-suite.info``);
  - [ ] metomi/rose#2144: display *further (optional) suite info* settings;
  - [ ] metomi/rose#2056: *resolve metadata division & duplication* across ``rose-suite.info`` & ``suite.rc``.

#### New feature requests (extensions):
- [ ] metomi/rose#2189: view multiple users at once on suites listing page.
- [ ] metomi/rose#2153: display auto-refresh icon on main/all pages.
- [ ] metomi/rose#1308: filter jobs by time run or updated.
- [ ] metomi/rose#1014: group by cycles &/or tasks in task list.
- [ ] metomi/rose#1013: store user preference.

#### Miscallenous issues:

- [ ] **https://github.com/cylc/cylc/pull/2614#issuecomment-433835346 Codacy issues (~350!) on Cylc Review exclusive web (HTML, JS & CSS) files**: sift through & either resolve or exclude from Codacy checks, as appropriate.
- [ ] **More comprehensive utility documentation**: currently there is only that from #2821.

#### Issues that are no longer issues (to close?):

* **metomi/rose#1310 & metomi/rose#1009 suite analytics & graphing**. Suite analytics will be implemented in the new Cylc GUI (#1873), but this is now being considered a separate domain to Bush/Review.
* metomi/rose#1030: given migration to Cylc, **historical ``rose suite-run`` logs no longer appropriate to display**?

**Comment by kinow** [comment]
I think all issues linked here have been closed @hjoliver @oliver-sanders ?

**Comment by hjoliver** [comment]
@wxtim might be the one to confirm this.
